import { Activity, ArrowRight, BrainCircuit, CalendarCheck, ChevronRight, CircleAlert, ClipboardCheck, FileSearch, MessageSquare, Sparkles, Stethoscope, UserPlus } from 'lucide-react'
import { dashboardStats, monitorCards, riskRows, taskRows } from '../mock/mockData'
import StatusTag from '../components/StatusTag'

const statIcons=[BrainCircuit,FileSearch,CircleAlert,CalendarCheck,UserPlus,ClipboardCheck,Activity,MessageSquare]
export default function Dashboard({onNavigate,onToast}:{onNavigate:(k:string)=>void;onToast:(m:string)=>void}) {
  return <><div className="dashboard-hero"><div><span><Sparkles size={15}/>AI 医疗运营工作台</span><h1>早上好，医学运营管理员</h1><p>今天有 <b>24 项</b>审核任务等待处理，其中 <em>4 项即将超时</em>。</p></div><button onClick={()=>onNavigate('reviews')}>查看待办中心 <ArrowRight/></button></div>
    <div className="stats">{dashboardStats.map(([name,value,trend],i)=>{const Icon=statIcons[i];return <div className={`stat s${i}`} key={name}><div><Icon/></div><span>{name}</span><b>{value}</b><small className={trend.includes('超时')||trend==='需关注'?'danger':''}>{trend}</small><i className="sparkline"/></div>})}</div>
    <section className="panel risks"><div className="panel-head"><div><h2>急症风险预警</h2><span>实时监测 · 今日已命中 18 次</span></div><button onClick={()=>onNavigate('consults')}>查看全部 <ChevronRight/></button></div>
      <div className="mini-table wide"><table><thead><tr><th>预警ID</th><th>用户</th><th>咨询主体</th><th>触发症状</th><th>命中规则</th><th>风险等级</th><th>AI 建议</th><th>已联系</th><th>处理状态</th><th>触发时间</th><th>操作</th></tr></thead>
        <tbody>{riskRows.map(r=><tr key={String(r.id)}><td><b>{String(r.id)}</b></td><td>{String(r.user)}</td><td>{String(r.subject)}</td><td>{String(r.symptom)}</td><td>{String(r.rule)}</td><td><StatusTag value={r.risk}/></td><td>{String(r.advice)}</td><td><StatusTag value={r.contacted}/></td><td><StatusTag value={r.status}/></td><td>{String(r.updatedAt).slice(5)}</td><td><div className="row-ops"><button onClick={()=>onNavigate('consults')}>查看会话</button><button onClick={()=>onToast('已转人工处理')}>转人工</button><button onClick={()=>onToast('预警已标记处理')}>标记已处理</button><button onClick={()=>onNavigate('rules')}>命中规则</button></div></td></tr>)}</tbody></table></div></section>
    <section className="panel task-table"><div className="panel-head"><div><h2>待办任务</h2><span>按 SLA 紧急程度排序 · 4 项即将超时</span></div><button onClick={()=>onNavigate('reviews')}>查看全部 <ChevronRight/></button></div>
      <div className="mini-table wide"><table><thead><tr><th>任务ID</th><th>任务类型</th><th>来源模块</th><th>关联对象ID</th><th>优先级</th><th>SLA剩余</th><th>负责人</th><th>处理状态</th><th>创建时间</th><th>操作</th></tr></thead><tbody>{taskRows.map(r=><tr key={String(r.id)}><td><b>{String(r.id)}</b></td><td>{String(r.type)}</td><td>{String(r.source)}</td><td>{String(r.object)}</td><td><StatusTag value={r.priority}/></td><td className="sla">{String(r.sla)}</td><td>{String(r.owner)}</td><td><StatusTag value={r.status}/></td><td>{String(r.updatedAt)}</td><td><div className="row-ops"><button onClick={()=>onToast('任务已领取')}>处理</button><button onClick={()=>onToast('已转派至医学审核组')}>转派</button><button onClick={()=>onNavigate('reviews')}>查看对象</button><button onClick={()=>onToast('任务已关闭')}>关闭</button></div></td></tr>)}</tbody></table></div></section>
    <div className="monitor-grid">{monitorCards.map(card=><section className="panel monitor" key={card.title}><div className="monitor-head"><div><h2>{card.title}</h2><span>{card.sub}</span></div><StatusTag value="实时"/></div><div className="monitor-main"><div><b>{card.value}</b><span style={{color:card.color}}>{card.delta}</span></div><MiniChart points={card.points} color={card.color}/></div><div className="monitor-legend">{card.legend.map(x=><div key={x[0]}><span>{x[0]}</span><b>{x[1]}</b></div>)}</div></section>)}</div>
    <div className="quick"><h2>常用功能</h2><div>{[['reports','上传检查报告'],['interpretation','报告 OCR 复核'],['archive','处理入档确认'],['rules','配置急症规则'],['agents','测试医生智能体'],['feedback','查看用户反馈']].map(([k,n])=><button key={k} onClick={()=>onNavigate(k)}><Stethoscope/><span>{n}</span><ChevronRight/></button>)}</div></div>
  </>
}
function MiniChart({points,color}:{points:number[];color:string}){
  const max=Math.max(...points),min=Math.min(...points),coords=points.map((p,i)=>`${i*45},${65-(p-min)/(max-min||1)*48}`).join(' ')
  return <svg className="mini-chart" viewBox="0 0 270 72" preserveAspectRatio="none"><defs><linearGradient id={`g${color.slice(1)}`} x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor={color} stopOpacity=".25"/><stop offset="1" stopColor={color} stopOpacity="0"/></linearGradient></defs><polygon points={`0,72 ${coords} 270,72`} fill={`url(#g${color.slice(1)})`}/><polyline points={coords} fill="none" stroke={color} strokeWidth="2.5"/>{points.map((p,i)=><circle key={i} cx={i*45} cy={65-(p-min)/(max-min||1)*48} r="2.5" fill="white" stroke={color} strokeWidth="2"/>)}</svg>
}
